# Generated by Django 4.0.5 on 2022-06-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_paquete_options_alter_paquete_image_set_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Image_Set_1',
            field=models.ImageField(upload_to='pack_profile'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='Image_Set_2',
            field=models.ImageField(upload_to='pack_profile'),
        ),
    ]
