# Generated by Django 4.0.5 on 2022-07-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_paquete_image_set_1_alter_paquete_image_set_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='precio_publico',
            field=models.IntegerField(),
        ),
    ]
